FROM hub.wangsonglin.com:8080/micro-service/openjdk:7-jre
MAINTAINER xxx xxx@163.com

COPY target/course-dubbo-service-1.0-SNAPSHOT.jar /course-service.jar

ENTRYPOINT ["java", "-jar", "/course-service.jar"]
